default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dollarmark_development
  password: password
test:
  <<: *default
  database: dollarmark_test

production:
  <<: *default
  database: dollarmark_production
  username: dollarmark
  password: <%= ENV['DOLLARMARK_DATABASE_PASSWORD'] %>