development: &default
  mode: sandbox
  client_id: <%= ENV["dollarlaunchclientid"] %>
  client_secret: <%= ENV["dollarlaunchclientsecret"] %>
test:
  <<: *default
production:
  mode: sandbox
  client_id: <%= ENV["dollarlaunchclientid"] %>
  client_secret: <%= ENV["dollarlaunchclientsecret"] %>